baseURL = "https://flicht.github.io/blog/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = ""
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"
publishDir = "docs"


[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Freddie Lichtenstein. [FredLich.](https:fredlich.com)"
  homeMetaContent = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
  footer = "Freddie Lichtenstein © 2019"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true

[menu]
  # [[menu.nav]]
  #   name = "Home"
  #   url = "/"
  #   weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
